@startuml

Class Bill1000Dispenser{
   -  IDispenseChain _nextChain
}
Class Bill500Dispenser
{
    - IDispenseChain _nextChain
}
Class Bill200Dispenser
{
    - IDispenseChain _nextChain
}
Class Bill100Dispenser
{
   - IDispenseChain _nextChain
}
Class Bill50Dispenser
{
    - IDispenseChain _nextChain
}

interface IDispenseChain
{
 + SetNextChain(IDispenseChain) : void
 + Dispense(Currency) : void
}
class ATM 
{
    + Dispense(Currency): void
}
class Currency
{
    - _amount : int
    + Currency(int) 
    + GetAmount() : int
}

Bill1000Dispenser .u.|> IDispenseChain
Bill500Dispenser .u.|> IDispenseChain
Bill200Dispenser .u.|> IDispenseChain
Bill100Dispenser .u.|> IDispenseChain
Bill50Dispenser .u.|> IDispenseChain

Bill1000Dispenser *-u-> IDispenseChain
Bill500Dispenser *-u-> IDispenseChain
Bill200Dispenser *-u-> IDispenseChain
Bill100Dispenser *-u-> IDispenseChain
Bill50Dispenser *-u-> IDispenseChain


Currency <-- IDispenseChain

ATM -r-> IDispenseChain

@enduml